version: '3.9'

services:
  orderprocessor:
    image: postgres:16-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: LocalDB@123Pass
  pgadmin:
    image: dpage/pgadmin4:8.9
    depends_on:
      - orderprocessor
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
volumes:
  pgdata:
