version: '3.9'

services:
  orderprocessor:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: LocalDB@123Pass
      POSTGRES_USER: postgres
